[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["web-push"]

[[scheduled]]
  path = "/.netlify/functions/send-reminders"
  schedule = "*/5 * * * *"  # untuk uji coba
